// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FundPool", b =>
                {
                    b.Property<int>("FundPoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FundPoolId"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FundPoolId");

                    b.HasIndex("UserId");

                    b.ToTable("FundPools");
                });

            modelBuilder.Entity("WebApplication1.Models.FundTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FundPoolId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricePerShare")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Shares")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("FundPoolId");

                    b.ToTable("FundTransactions");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.StockPrice", b =>
                {
                    b.Property<int>("StockPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StockPriceId"));

                    b.Property<decimal>("Close").HasColumnType("decimal(65,30)");
                    b.Property<decimal?>("High").HasColumnType("decimal(65,30)");
                    b.Property<decimal?>("Low").HasColumnType("decimal(65,30)");
                    b.Property<decimal?>("Open").HasColumnType("decimal(65,30)");
                    b.Property<DateOnly>("PriceDate").HasColumnType("date");
                    b.Property<string>("StockCode").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                    b.Property<string>("Ticker").IsRequired().HasMaxLength(30).HasColumnType("varchar(30)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime(6)");
                    b.Property<long?>("Volume").HasColumnType("bigint");

                    b.HasKey("StockPriceId");
                    b.HasIndex("StockCode", "PriceDate").IsUnique();
                    b.ToTable("stockprices");
                });

            modelBuilder.Entity("FundPool", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("FundPools")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.FundTransaction", b =>
                {
                    b.HasOne("FundPool", "FundPool")
                        .WithMany("Transactions")
                        .HasForeignKey("FundPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundPool");
                });

            modelBuilder.Entity("FundPool", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("FundPools");
                });
#pragma warning restore 612, 618
        }
    }
}
